applications/machine/urls.py
from django.urls import path

from . import views

app_name = 'machines_app'

urlpatterns = [
    path(
        '',
        views.MachinesList.as_view(),
        name='all_machines'
        ),
    path('nueva_maquina/',
         views.AddMachineView.as_view(),
         name="add_machine"
         ),
    path('editar_maquina/<pk>/',
         views.EditMachineView.as_view(),
         name="edit_machine"
    ),
]

applications/session/urls.py
from django.urls import path

from . import views

app_name = 'sessions_app'

urlpatterns = [
    path(
        '',
        views.SessionsList.as_view(),
        name='all_sessions'
    ),
    path('nueva_session/',
         views.AddSessionView.as_view(),
         name="add_sessions"
    ),
    path('editar_session/<pk>/',
         views.EditSessionView.as_view(),
         name="edit_sessions"
    ),
    path('nueva_sesion_de_tiempo/',
         views.AddTimeSessionView.as_view(),
         name="add_time_sessions"
    ),
]

gym_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('allauth.urls')),
    # path('', include('applications.user.urls')),
    path('admin/', admin.site.urls),
    path('sesiones/', include('applications.session.urls')),
    path('maquinas/', include('applications.machine.urls')),
    path('home/', include('applications.home.urls')),
]

applications/machine/models.py
from django.db import models
from applications.muscle.models import Muscle


# Create your models here.

class MachineBrand(models.Model):
    name = models.CharField("Marca", max_length=40, null=False, blank=False)

    class Meta:
        verbose_name = 'Marca de máquina'
        verbose_name_plural = 'Marcas de máquinas'

    def __str__(self):
        return self.name


class Machine(models.Model):
    MACHINE_TYPE_OPTIONS = (
        (0, 'REPS'),
        (1, 'TIME'),
    )

    name = models.CharField("Nombre de la máquina", max_length=40, null=False, blank=False)
    type = models.IntegerField("REPS/TIEMPO", choices=MACHINE_TYPE_OPTIONS, default=0)
    muscle = models.ManyToManyField("muscle.Muscle", blank=True, null=True)
    brand = models.ForeignKey(MachineBrand, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Máquina'
        verbose_name_plural = 'Máquinas'

    def __str__(self):
        return str(self.brand) + " - " + self.name

applications/session/models.py
from django.db import models
from django.utils.timezone import now

from applications.machine.models import Machine


# Create your models here.


class Session(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    uploading_time = models.DateTimeField("Fecha de carga", default=now)

    class Meta:
        verbose_name = 'Sesión'
        verbose_name_plural = 'Sesiones'

    def __str__(self):
        return str(self.machine) + " - " + str(self.uploading_time)

class Series(models.Model):
    reps = models.PositiveIntegerField("Repeticiones", blank=False, null=False)
    intensity = models.PositiveIntegerField("Intesidad/Peso")
    session = models.ForeignKey(Session, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Serie'
        verbose_name_plural = 'Series'

    def __str__(self):
        return str(self.session) + " - " + str(self.reps)


class TimeSession(Session):
    time = models.DurationField("Tiempo", blank=False, null=False)
    spending = models.FloatField("Gasto/Calorías", default=0)

    class Meta:
        verbose_name = 'Sesión de tiempo'
        verbose_name_plural = 'Sesiones de tiempo'

    def __str__(self):
        return str(self.machine) + " - " + str(self.time)

applications/session/forms.py
from django import forms
from .models import Session, TimeSession


class BaseSessionForm(forms.ModelForm):
    class Meta:
        model = Session
        fields = (
            'machine',
        )

        widgets = {
            'machine': forms.Select(
                attrs={
                    'id': 'id_machine',
                    'class': 'form-control',
                }
            ),
        }


class AddSessionForm(BaseSessionForm):
    pass


class EditSessionForm(BaseSessionForm):
    pass


class AddTimeSessionForm(BaseSessionForm):
    class Meta(BaseSessionForm.Meta):
        model = TimeSession
        fields = BaseSessionForm.Meta.fields + (
            'time',
            'spending',
        )
        widgets = BaseSessionForm.Meta.widgets | {
            'time': forms.TimeInput(
                attrs={
                    'id': 'id_time',
                    'class': 'form-control',
                    'type': 'time',
                    'step': 1,
                    'max': '02:00:00',
                }
            ),
            'spending': forms.NumberInput(
                attrs={
                    'id': 'id_spending',
                    'class': 'form-control',
                }
            ),
        }


class EditTimeSessionForm(BaseSessionForm):
    pass

applications/session/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView,
                                  ListView,
                                  UpdateView,)

from .forms import (AddSessionForm,
                    EditSessionForm,
                    AddTimeSessionForm,
                    EditTimeSessionForm,
                    )

from .models import Session, TimeSession


# Create your views here.
class SessionsList(LoginRequiredMixin, ListView):
    template_name = 'session/list_all.html'
    paginate_by = 10
    ordering = 'id'
    model = Session
    login_url = reverse_lazy('users_app:login')


class AddSessionView(LoginRequiredMixin, CreateView):
    template_name = 'session/add_session.html'
    model = Session
    form_class = AddSessionForm
    success_url = reverse_lazy('sessions_app:all_sessions')
    login_url = reverse_lazy('users_app:login')

    def form_valid(self, form):
        form.cleaned_data["uploading_time"] = datetime.datetime.now()
        return super(AddSessionView, self).form_valid(form)


class EditSessionView(LoginRequiredMixin, UpdateView):
    template_name = 'session/edit_session.html'
    model = Session
    form_class = EditSessionForm
    success_url = reverse_lazy('sessions_app:all_sessions')
    login_url = reverse_lazy('users_app:login')


class AddTimeSessionView(LoginRequiredMixin, CreateView):
    template_name = 'session/add_time_session.html'
    model = TimeSession
    form_class = AddTimeSessionForm
    success_url = reverse_lazy('sessions_app:all_sessions')
    login_url = reverse_lazy('users_app:login')


class EditTimeSessionView(LoginRequiredMixin, UpdateView):
    template_name = 'session/edit_time_session.html'
    model = TimeSession
    form_class = EditTimeSessionForm
    success_url = reverse_lazy('sessions_app:all_sessions')
    login_url = reverse_lazy('users_app:login')

templates/session/add_session.html
{% extends 'base_template.html' %}
{% block title %}
Nueva Sesión
{% endblock %}

{% block fillable %}

<h1>Nueva Sesión</h1>
{% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
{% endif %}
<form class="needs-validation" novalidate method="POST">{% csrf_token %}
    <div class="row mb-3">
        <div class="col-3">
            <label for="id_machine" class="form-label">Maquina:</label>
            {{ form.machine }}
        </div>

    </div>







    <button type="submit" class="btn btn-primary">Guardar Sesión</button>
</form>




{% endblock %}

templates/session/add_time_session.html
{% extends 'base_template.html' %}
{% block title %}
Nueva Sesión de tiempo
{% endblock %}

{% block fillable %}

<h1>Nueva Sesión de tiempo</h1>
{% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
{% endif %}
<form class="needs-validation" novalidate method="POST">{% csrf_token %}
    <div class="row mb-3">
        <div class="col-3">
            <label for="id_machine" class="form-label">Maquina:</label>
            {{ form.machine }}
        </div>

        <div class="col-3">
            <label for="id_time" class="form-label">Tiempo:</label>
            {{ form.time }}
        </div>

        <div class="col-3">
            <label for="id_spending" class="form-label">Gasto/calorías:</label>
            {{ form.spending }}
        </div>

    </div>







    <button type="submit" class="btn btn-primary">Guardar Sesión</button>
</form>




{% endblock %}

templates/session/edit_session.html
{% extends 'base_template.html' %}
{% block title %}
Editar Sesión
{% endblock %}

{% block fillable %}

<h1>Editar Sesión</h1>
{% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
{% endif %}
<form class="needs-validation" novalidate method="POST">{% csrf_token %}
    <div class="row mb-3">
        <div class="col-3">
            <label for="id_machine" class="form-label">Maquina:</label>
            {{ form.machine }}
        </div>

    </div>







    <button type="submit" class="btn btn-primary">Guardar Sesión</button>
</form>




{% endblock %}

templates/session/list_all.html
{% extends 'base_template.html' %}

{% block fillable %}
    <h1>Lista de Sesiones</h1>


    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Nombre</th>
                <th scope="col">REPS/TIEMPO</th>
                <th scope="col">Opciones</th>
            </tr>
        </thead>
        <tbody>
        {% for o in object_list %}
            {{ o.id_for_label }}
             <tr>
                <td>{{ o.id }}</td>
                <td>{{ o.name }}</td>
                <td>{{ o.get_type_display }}</td>
                <td>
                    <div>
{#                        <a type="button" class="btn btn-warning" href="{% url 'machines_app:edit_machine' o.id %}">Editar</a>#}
                    </div>
                </td>
             </tr>
        {% endfor %}

        </tbody>
    </table>

    {% include 'includes/pagination.html' %}
{% endblock fillable %}