applications/home/urls.py
from django.urls import path

from . import views

app_name = "home_app"
urlpatterns = [
    path(
        '',
        views.HomeView.as_view(),
        name='home'
    )

    ]

applications/machine/urls.py
from django.urls import path

from . import views

app_name = 'machines_app'

urlpatterns = [
    path(
        '',
        views.MachinesList.as_view(),
        name='all_machines'
        ),
    path('nueva_maquina/',
         views.AddMachineView.as_view(),
         name="add_machine"
         ),
    path('editar_maquina/<pk>/',
         views.EditMachineView.as_view(),
         name="edit_machine"
    ),
]

applications/session/urls.py
from django.urls import path

from . import views

app_name = 'sessions_app'

urlpatterns = [
    path(
        '',
        views.SessionsList.as_view(),
        name='all_sessions'
    ),
    path('nueva_session/',
         views.AddSessionView.as_view(),
         name="add_sessions"
    ),
    path('editar_session/<pk>/',
         views.EditSessionView.as_view(),
         name="edit_sessions"
    ),
    path('nueva_sesion_de_tiempo/',
         views.AddTimeSessionView.as_view(),
         name="add_time_sessions"
    ),
]

gym_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('allauth.urls')),
    # path('', include('applications.user.urls')),
    path('admin/', admin.site.urls),
    path('sesiones/', include('applications.session.urls')),
    path('maquinas/', include('applications.machine.urls')),
    path('home/', include('applications.home.urls')),
]

templates/includes/comunas_dropdown.html
<option value="">---------</option>
    {% for comuna in comunas %}
    <option value="{{ comuna.pk }}">{{ comuna.name }}</option>
    {% endfor %}

templates/includes/nav_bar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
{#        <a class="navbar-brand" href="#">Navbar</a>#}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
{#            <ul class="navbar-nav me-auto mb-2 mb-lg-0">#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link active" aria-current="page" href="#">Home</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="#">Link</a>#}
{#                </li>#}
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">#}
{#                    Dropdown#}
{#                    </a>#}
{#                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#                        <li><a class="dropdown-item" href="#">Action</a></li>#}
{#                        <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#                        <li><hr class="dropdown-divider"></li>#}
{#                        <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#                    </ul>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
{#                </li>#}
{#            </ul>#}

            <ul class="navbar-nav ms-auto d-flex flex-row">

{#                <li class="nav-item">#}
{#                    <form class="d-flex">#}
{#                        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Buscar">#}
{#                        <button class="btn btn-outline-success" type="submit">Buscar</button>#}
{#                    </form>#}
{#                </li>#}


                <li class="nav-item dropdown">

                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user }}
                        <i class="bi bi-person-circle"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
{#                        <li><a class="dropdown-item" href="#">Action</a></li>#}
                        <li><a class="dropdown-item" href="{% url 'socialaccount_connections' %}">Configuración de login externo</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'account_logout' %}">Cerrar Sesión</a></li>
                    </ul>
                </li>
{#                    <li class="nav-item dropdown">#}
{#                        <a class="nav-link dropdown-toggle " href="#"#}
{#                          id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">#}
{#                          <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img (31).webp" class="rounded-circle"#}
{#                            height="22" alt="Avatar" loading="lazy" />#}
{#                        </a>#}
{#                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">#}
{#                          <li><a class="dropdown-item" href="#">My profile</a></li>#}
{#                          <li><a class="dropdown-item" href="#">Settings</a></li>#}
{#                          <li><a class="dropdown-item" href="#">Logout</a></li>#}
{#                        </ul>#}
{#                    </li>#}
            </ul>
        </div>
    </div>
</nav>

templates/includes/pagination.html
{% if page_obj.has_other_pages %}
    <nav aria-label="...">
        <ul class="pagination">
        {% if page_obj.has_previous %}

        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Anterior</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="" tabindex="-1" aria-disabled="true">Anterior</a>
        </li>
        {% endif %}

        {% for i in paginator.page_range %}
        {% if i == page_obj.number %}
            <li class="page-item  active " aria-current="page">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
        {% else %}
            <li class="page-item" aria-current="page">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>

        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}


        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
        </li>

        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="">Siguiente</a>
        </li>
        {% endif %}

        </ul>
    </nav>
{% endif %}

templates/includes/script_comunas.html
<script>
    $("#id_region").change(function () {
      var url = '{% url 'locations_app:comunas' %}';  // get the url of the `load_cities` view
      var regionId= $(this).val();  // get the selected country ID from the HTML input
      $.ajax({                       // initialize an AJAX request
        url: '{% url 'locations_app:comunas' %}',                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'region': regionId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_comuna").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
</script>

templates/includes/script_rut_applicants.html
<script>
    $('#id_run').rut({
       fn_validado:function (a) {

         var run= $('#id_run').val();  // get the selected country ID from the HTML input
           console.log(run)
          $.ajax({                       // initialize an AJAX request
            url: '{% url 'applicants_app:check_rut_applicant' %}',                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
              'rut': run       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
              console.log(data);  // replace the contents of the city input with the data that came from the server
            }
          });

        }
    });
</script>

templates/includes/sidebar.html
{% load static %}
    <script src="{%  static 'js/sidebars.js' %}"></script>
    <link rel="stylesheet" href="{%  static 'css/sidebars.css' %}">



<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;min-height: 100vh; position: fixed">
    <a href="{% url 'home_app:home' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">

        <div class="text-center">
{#            <img src="{% static 'img/Logo-myra-web.png' %}" title="Logo-myra-web" alt="Logo-myra-web" width="50%" class="mx-auto">#}
        </div>
    </a>
    
    <hr>
    <ul class="list-unstyled ps-0">
        <li class="mb-1">
            <a href="{% url 'home_app:home' %}" class="btn btn-toggle align-items-center rounded text-white">Home</a>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed text-white" data-bs-toggle="collapse" data-bs-target="#applicants-collapse" aria-expanded="false" >
                Sesiones
            </button>
            <div class="collapse" id="applicants-collapse">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="{% url 'sessions_app:all_sessions' %}" class="link-light rounded">Ver Sesiones</a></li>
                    <li><a href="{% url 'sessions_app:add_sessions' %}" class="link-light rounded">Nueva Sesión</a></li>
                    <li><a href="{% url 'sessions_app:add_time_sessions' %}" class="link-light rounded">Nueva Sesión de tiempo</a></li>
                </ul>
            </div>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed text-white" data-bs-toggle="collapse" data-bs-target="#opportunities-collapse" aria-expanded="false">
                Máquinas
            </button>
            <div class="collapse" id="opportunities-collapse">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="{% url 'machines_app:all_machines' %}" class="link-light rounded">Ver Máquinas</a></li>
                    <li><a href="{% url 'machines_app:add_machine' %}" class="link-light rounded">Añadir Máquina</a></li>
                </ul>
            </div>
        </li>
{#            <li class="border-top my-3"></li>#}
{#            <li class="mb-1">#}
{#                <button class="btn btn-toggle align-items-center rounded collapsed text-white" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">#}
{#                    Account#}
{#                </button>#}
{#                <div class="collapse" id="account-collapse">#}
{#                    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">#}
{#                        <li><a href="#" class="link-light rounded">New...</a></li>#}
{#                        <li><a href="#" class="link-light rounded">Profile</a></li>#}
{#                        <li><a href="#" class="link-light rounded">Settings</a></li>#}
{#                        <li><a href="#" class="link-light rounded">Sign out</a></li>#}
{#                    </ul>#}
{#                </div>#}
{#            </li>#}

    </ul>
</div>